create table
public.timeline (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone null default now(),
  start_date date not null,
  title text null,
  body text null,
  image text null,
  image_credit text null,
  constraint timeline_pkey primary key (id),
  constraint timeline_id_key unique (id)
) tablespace pg_default;
