create table
public.timelines (
  id bigint generated by default as identity primary key not null,
  created_at timestamp with time zone null default now(),
  name text not null
) tablespace pg_default;

create policy "Enable read access for all users" on public.timelines
as permissive for select to public
using (true);

create policy "Enable insert access for authenticated users only" on public.timelines
as permissive for insert to authenticated
with check (true);

create policy "Enable update access for authenticated users only" on public.timelines
as permissive for update to authenticated
using (true)
with check (true);

create policy "Enable delete access for authenticated users only" on public.timelines
as permissive for delete to authenticated
using (true);

alter table public.timelines enable row level security;


alter table public.timeline
  add column if not exists timeline bigint not null references public.timelines(id);


insert into public.timelines (name) values ('Niagara-on-the-lake');
update public.timeline set timeline=(select id from public.timelines where name='Niagara-on-the-lake');
