create table
public.timeline (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone null default now(),
  start_date date not null,
  title text null,
  body text null,
  image text null,
  image_credit text null,
  constraint timeline_pkey primary key (id),
  constraint timeline_id_key unique (id)
) tablespace pg_default;

create policy "Enable read access for all users" on public.timeline
as permissive for select to public
using (true);

create policy "Enable insert access for authenticated users only" on public.timeline
as permissive for insert to authenticated
with check (true);

create policy "Enable update access for authenticated users only" on public.timeline
as permissive for update to authenticated
using (true)
with check (true);

create policy "Enable delete access for authenticated users only" on public.timeline
as permissive for delete to authenticated
using (true);

alter table public.timeline enable row level security;
